#!bin/bash

function parse_git_branch() {
    git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/ (󰘬 \1)/p'
}

function git_status() {
    echo "${COLOR_DEF}${$(~/.config/zsh/gs)}${COLOR_DEF}"
}

# \u{001B}[38;2;{};{};{}m
COLOR_DEF=$'%f'
COLOR_USR=$'%F{243}'
COLOR_DIR=$'%F{221}'
COLOR_GIT_BRANCH=$'%F{45}'
COLOR_GIT_STATUS=$'%F{32}'
setopt PROMPT_SUBST
export PROMPT='${COLOR_USR}%n ${COLOR_DIR}%~${COLOR_GIT_BRANCH}$(parse_git_branch)${COLOR_GIT_STATUS} ${COLOR_DEF}[$(git_status)]${COLOR_DEF} >> '
