#!/bin/bash

if ! command -v asdf &> /dev/null
then
    echo
    echo "Install webp!"
    read -p "Want me to do it for you? [y/n]: " ans
    if [ $ans = "n" ] || [ $ans = "N" ] || [ $ans = "no" ] || [ $ans = "No" ] || [ $ans = "NO" ]; then
        echo "Alright.🙌"
    fi
fi


WALLPAPERS=~/Pictures/Wallpapers/

if [ ! -d $WALLPAPERS ]; then
    echo "$WALLPAPERS does not exist!!!"
    echo
    exit
fi

ans=""
echo
read -p "Do you want to remove original files? [y/n]: " ans
if [ $ans = "n" ] || [ $ans = "N" ] || [ $ans = "no" ] || [ $ans = "No" ] || [ $ans = "NO" ]; then
    echo "---- Not removing originals ----"
fi

for w in $WALLPAPERS/*; do
    if [ ! -f "$w" ]; then
        continue
    fi

    filename=$(basename -- "$w")
    extension="${filename##*.}"
    filename="${filename%.*}"

    if [ $extension != "webp" ] && [ $filename != ".DS_STORE" ]; then
        echo
        echo "converting:   $w"
        cwebp -near_lossless 16 -mt -quiet $w -o $WALLPAPERS/$filename.webp
        if [ $ans = "y" ] || [ $ans = "Y" ] || [ $ans = "yes" ] || [ $ans = "Yes" ] || [ $ans = "YES" ]; then
            echo "removing:     $w"
            trash $w
        fi
        echo
    fi
done
