#!/bin/bash

WALLPAPERS=~/Pictures/Wallpapers

if [ ! -d $WALLPAPERS ]; then
    echo "$WALLPAPERS does not exist!!!"
    echo
    exit
fi

ans="n"
if [ "$1" = "-r" ]; then
    echo
    read -p 'Are you sure you want to remove original files? [y/n]: ' ans
    if [ $ans = "n" ] || [ $ans = "N" ] || [ $ans = "no" ] || [ $ans = "No" ] || [ $ans = "NO" ]; then
        echo "Not removing originals."
    fi
fi
for w in $WALLPAPERS/*; do
    filename=$(basename -- "$w")
    extension="${filename##*.}"
    filename="${filename%.*}"

    if [ $extension != "webp" ] && [ $filename != ".DS_STORE" ]; then
        echo
        echo "converting:   $w"
        cwebp -near_lossless 16 -mt -quiet $w -o $WALLPAPERS/$filename.webp
        if [ $ans = "y" ] || [ $ans = "Y" ] || [ $ans = "yes" ] || [ $ans = "Yes" ] || [ $ans = "Yes" ]; then
            echo "removing:     $w"
            trash $w
        fi
        echo
    fi
done
