return {
--     "lukas-reineke/indent-blankline.nvim",
--     main = "ibl",
--     ---@module "ibl"
--     ---@type ibl.config
--     config = function()
--         require("ibl").setup({
--             indent = {
--                 -- '▏'
--                 -- '▎'
--                 -- '▍'
--                 char = { '│' }
--             },
--             scope = {
--                 exclude = {
--                     language = {
--                         "rust",
--                         "typescript",
--                         "javascript",
--                         "lua",
--                         "go",
--                         "c",
--                         "cpp",
--                         "zig",
--                     }
--                 }
--             },
--         })
--     end
}
