#!/bin/bash
echo ------------- Running Script -------------
echo
rm ./o/*

for font in `ls ./i | grep 'otf\|ttf'`; do
    fontforge -script ./nerd-fonts-patcher/font-patcher $font -s -l -c --quiet --careful -out o
    echo 'Patched: ${font}'
    echo
done
