#!/bin/bash

flag=0
for font in `ls $search_dir | grep otf`; do
    if [ $flag == 0 ]
    then
        flag = 1
        mkdir output
    fi

    fontforge -script ./nerd-fonts-patcher/font-patcher $font -s -l --quiet --fontawesome --fontawesomeextension --octicons --powersymbols --powerline --mdi --weather --careful -out output
    echo ------------- $font -------------
done
